apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-k8s-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/kpblmMik/example-k8s-application.git"
    path: "./deployment"
    targetRevision: "HEAD"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "default"
  syncPolicy:
    automated:
      prune: true
